[package]
name = "fftw"
version = "0.8.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

description = "safe wrapper of FFTW3"
repository = "https://github.com/rust-math/fftw"
keywords = ["fftw"]
license-file = "../LICENSE.md"

[features]
default = ["source"]
system = ["fftw-sys/system"]
source = ["fftw-sys/source"]
intel-mkl = ["fftw-sys/intel-mkl"]
threads = ["source", "fftw-src/threads"]

[dependencies]
bitflags = "2.2.1"
lazy_static = "1.4.0"
ndarray = "0.15.6"
num-complex = "0.4.3"
num-traits = "0.2.15"
thiserror = "1.0.40"

[dependencies.fftw-sys]
path = "../fftw-sys"
version = "0.8.0"
default-features = false

[package.metadata.docs.rs]
no-default-features = true
features = ["system"]
